name: Build Documentation

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"

      - name: Install dependencies
        run: |
          uv pip install --system -e .

      - name: Build documentation
        run: |
          poe docs

      - name: Upload Documentation
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: build/
          retention-days: 7
